spring:
  application:
    name: gateway

server:
  port: 8808

zuul:
  routes:
    users-api:
      path: /api/**
      serviceId: user-modules

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:20000/eureka/

jwt:
  token:
    issuer: zhangaoo.com
    expiredMinutes: 60
    refreshExpiredMinutes: 480
    signingKey: ${random.value}